# Generated by Django 4.2 on 2023-08-30 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_review_image_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
    ]
